### PR TITLE
Grammar corrections in en.yml

### PR DESCRIPTION
**Pull request by imneokittyy**

### CODE REVIEW

**Comment by imneokittyy** [comment]
https://github.com/gmankab/anarchy_bot/issues/1

**Comment by flippoinzaghi7** [comment]
hello neo do u remember me?

**Comment by flippoinzaghi7** [comment]
@imneokittyy

**Comment by flippoinzaghi7** [comment]
my name is Kutay ur turkish friend also u were sometimes calling me "kutas" if you contact me @slimshadyisnotreal (on telegram) i will be so happy i miss you dude

**Comment by flippoinzaghi7** [comment]
@imneokittyy

**Comment by gmankab** [comment]
i miss neokitty too (((

**Comment by flippoinzaghi7** [comment]
@imneokittyy

**Pull request merged**
